### ISSUE TITLE
EndPoint BattlePass

### ISSUE THREAD

**Issue by SamueldaCostaAraujoNunes** [Valorant-API/java-library#3]
I'm a developer of the App [Battle Pass Calculator for VALORANT](https://github.com/SamueldaCostaAraujoNunes/BattlePass-Calculator-for-VALORANT) unfortunately, the Riot API doesn't support the current Battle Pass data, usually I collect all the data manually. I would like to know, if it is possible to create an endpoint that returns all the rewards of the pass? passing as a parameter the id of the act / episode.

How I use it today:
[passe.json](https://github.com/SamueldaCostaAraujoNunes/BattlePass-Calculator-for-VALORANT/blob/master/app/src/main/res/raw/passe.json)

**Comment by BobbyESP** [comment]
Hi, Samuel. I recommend you to see this GitHub repo: [THIS](https://github.com/techchrism/valorant-api-docs) (it's not mine, but if u like it, pls star it)

For you, i think it will be very useful.
I were searching and the endpoint that you need maybe it's this, but i'm not sure: [THIS](https://www.github.com/techchrism/valorant-api-docs/tree/trunk/docs%2FContracts%2FGET%20ContractDefinitions_FetchActiveStory.md)
Thank you!

**Comment by SamueldaCostaAraujoNunes** [comment]
I think it fits what I need, thanks!
